"""add skipped_update to scrape_runs

Revision ID: ae99a1939dc1
Revises: e2835a568ade
Create Date: 2026-07-29 02:58:26.035382+00:00

Re-parented 2026-08-05: originally chained off ``5ee285a3c724`` (prod head at
authoring time), but main's head moved to ``a3c32c2aa4d3`` (#224) and then to
``e2835a568ade`` (the fireworksai/thinkingmachines repoint, PR #236). Chaining
off ``e2835a568ade`` keeps a single head with the agreed merge order: #236
first, then this branch.

Persists the scraper safety-guard signal. Until now ``result.skipped_update``
was computed and then thrown away, so a truncated run landed in
``scrape_runs`` with ``error_count=0`` — indistinguishable from a perfect
run. That is why Apple's seven truncations in 21 days went unnoticed.

Migration safety: a SINGLE nullable column, NO server default, NO backfill.
Postgres therefore records this as a catalog-only change — it does not
rewrite the table and does not touch the heap, so it is safe on the large
production ``scrape_runs`` table. This is deliberately the same shape as
``5ee285a3c724`` and ``0fa33aca5bda``; see
``docs/incidents/2026-04-18-migration-filled-postgres-volume/`` for the
incident that made table rewrites a hard no.

NULL is meaningful: it means "this row was written before the column
existed", not "the guard did not trip". A ``server_default='false'`` would
have retroactively asserted that the seven real Apple skips were clean runs.

No index is bundled here on purpose — index creation is a separate,
separately-reviewable operation.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae99a1939dc1'
down_revision: Union[str, None] = 'e2835a568ade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('skipped_update', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'skipped_update')
    # ### end Alembic commands ###
