"""custom company sources (E7 Phase 1) — visibility cols, user_companies,
company_scripts, company_harvests, company_add_attempts, scrape_runs cols

Autogenerated, then reviewed per src/backend/CLAUDE.md:
  - collapsed the seven ``companies`` column adds and the two ``scrape_runs``
    column adds into ONE combined, catalog-only ALTER TABLE each (every column
    is nullable OR has a constant server default -> a metadata-only change, no
    table rewrite regardless of row count; see
    docs/incidents/2026-04-18-migration-filled-postgres-volume/ and the
    experience_level/is_remote_eligible precedent in 5ee285a3c724).

All four new tables are empty at create time, so their creation is free. The
partial index ``ix_companies_visibility`` only ever indexes the handful of
private 'user' rows.

Revision ID: fb8467065dfc
Revises: b4e1c9d77a02
Create Date: 2026-08-09 18:33:09.607924+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb8467065dfc'
down_revision: Union[str, None] = 'b4e1c9d77a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_add_attempts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('submitted_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('resolved_ats', sa.Text(), nullable=True),
    sa.Column('board_token', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_add_attempts_user_id', 'company_add_attempts', ['user_id'], unique=False)
    op.create_table('company_harvests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('verdict_reason', sa.Text(), nullable=True),
    sa.Column('records_harvested', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('declared_total', sa.Integer(), nullable=True),
    sa.Column('oracle_total', sa.Integer(), nullable=True),
    sa.Column('oracle_kind', sa.Text(), nullable=False),
    sa.Column('cap_hit', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('page_advance_ok', sa.Boolean(), nullable=True),
    sa.Column('id_dedup_dropped', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tolerance_used', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_harvests_company_started_at', 'company_harvests', ['company_id', 'started_at'], unique=False)
    op.create_table('company_scripts',
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('script', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('script_version', sa.Integer(), nullable=False),
    sa.Column('transport', sa.Text(), nullable=False),
    sa.Column('oracle_kind', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('user_companies',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=False),
    sa.Column('canonical_source_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'company_id'),
    sa.UniqueConstraint('user_id', 'canonical_source_key', name='uq_user_companies_source_key')
    )
    op.create_index('idx_user_companies_company_id', 'user_companies', ['company_id'], unique=False)
    # One combined, catalog-only ALTER TABLE (every column nullable or with a
    # constant server default -> no table rewrite regardless of row count).
    op.execute(
        """
        ALTER TABLE companies
            ADD COLUMN visibility           TEXT NOT NULL DEFAULT 'public',
            ADD COLUMN cadence_hours        INTEGER,
            ADD COLUMN next_run_at          TIMESTAMP WITH TIME ZONE,
            ADD COLUMN tracking_started_at  TIMESTAMP WITH TIME ZONE,
            ADD COLUMN health_state         TEXT,
            ADD COLUMN last_success_at      TIMESTAMP WITH TIME ZONE,
            ADD COLUMN consecutive_failures INTEGER NOT NULL DEFAULT 0
        """
    )
    op.create_index('ix_companies_visibility', 'companies', ['visibility'], unique=False, postgresql_where=sa.text("visibility <> 'public'"))
    # One combined, catalog-only ALTER TABLE on the ~455k-row scrape_runs table.
    op.execute(
        """
        ALTER TABLE scrape_runs
            ADD COLUMN source_id TEXT,
            ADD COLUMN success   BOOLEAN
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE scrape_runs
            DROP COLUMN success,
            DROP COLUMN source_id
        """
    )
    op.drop_index('ix_companies_visibility', table_name='companies', postgresql_where=sa.text("visibility <> 'public'"))
    op.execute(
        """
        ALTER TABLE companies
            DROP COLUMN consecutive_failures,
            DROP COLUMN last_success_at,
            DROP COLUMN health_state,
            DROP COLUMN tracking_started_at,
            DROP COLUMN next_run_at,
            DROP COLUMN cadence_hours,
            DROP COLUMN visibility
        """
    )
    op.drop_index('idx_user_companies_company_id', table_name='user_companies')
    op.drop_table('user_companies')
    op.drop_table('company_scripts')
    op.drop_index('idx_company_harvests_company_started_at', table_name='company_harvests')
    op.drop_table('company_harvests')
    op.drop_index('idx_company_add_attempts_user_id', table_name='company_add_attempts')
    op.drop_table('company_add_attempts')
    # ### end Alembic commands ###
