"""add experience_level/is_remote_eligible cols to job_listings

Autogenerated, then reviewed per src/backend/CLAUDE.md:
  - collapsed the two job_listings column adds into ONE combined, catalog-only
    ALTER TABLE (both nullable, no default backfill -> a metadata-only change,
    no table rewrite regardless of row count; see
    docs/incidents/2026-04-18-migration-filled-postgres-volume/ and the
    enrichment-column precedent in 0fa33aca5bda).

These two columns are denormalized copies of the only two ``details`` JSONB
sub-fields the ``/api/jobs`` list path serves. Reading ``details->'…'`` detoasts
the full ~10 KB ``details`` value per row; on the batched list query (~12k rows)
that ~100 MB of TOAST reads blew past the 30 s statement timeout (2026-07-13
outage). The read path now sources both values from these columns, so it never
touches ``details``/TOAST. No backfill: the upsert write path populates them for
every re-seen OPEN job on the next scrape cycle (mirrors the enrichment columns).

Revision ID: 5ee285a3c724
Revises: 01fef5c9c582
Create Date: 2026-07-13 14:39:30.386206+00:00

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5ee285a3c724'
down_revision: Union[str, None] = '01fef5c9c582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # One combined, catalog-only ALTER TABLE (both nullable, no default -> no
    # table rewrite regardless of row count).
    op.execute(
        """
        ALTER TABLE job_listings
            ADD COLUMN experience_level   TEXT,
            ADD COLUMN is_remote_eligible BOOLEAN
        """
    )


def downgrade() -> None:
    op.execute(
        """
        ALTER TABLE job_listings
            DROP COLUMN is_remote_eligible,
            DROP COLUMN experience_level
        """
    )
