"""add guard_reason to scrape_runs

Revision ID: 888b007b89fa
Revises: ae99a1939dc1
Create Date: 2026-07-29 04:25:52.113904+00:00

Records WHICH safety-guard rule tripped: NULL | 'empty_scrape' |
'partial_scrape'.

Not redundant with ``skipped_update`` (added in ae99a1939dc1). BOTH guard
rules set that boolean, so it cannot distinguish a total scraper outage —
rule (a), which is documented as never auto-released — from an
Apple-style truncation, which is the only thing the bounded auto-release
may count as evidence. Counting the boolean meant three dead-scraper runs
(0, 0, 0) released the very next truncated run outright, with no
repetition behind it.

Migration safety: a SINGLE nullable column, NO server default, NO
backfill — catalog-only, no table rewrite, same shape as ae99a1939dc1 and
5ee285a3c724. See docs/incidents/2026-04-18-migration-filled-postgres-volume/.

NULL is meaningful and is treated as a hard stop by
``database.count_consecutive_partial_skips``: it means "written before
this column existed", i.e. unknown, and an unknown must never count as
evidence toward releasing a destructive guard.

The companion index lives in its OWN revision (b4e1c9d77a02), not here —
index creation is a separately-reviewable operation with a different
operational risk profile.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888b007b89fa'
down_revision: Union[str, None] = 'ae99a1939dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('guard_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'guard_reason')
    # ### end Alembic commands ###
