"""launch radar pr requests

Revision ID: b7c4d1370996
Revises: 33ff7e590a46
Create Date: 2026-10-09 02:36:06.039336+00:00

``launch_radar_pr_requests``: one row per Launch Radar card that tracks the
add-company PR the nightly loop opens for a SAVED card
(docs/implementations/launch-radar/saved-pr/PLAN.md §1). Autogenerated from
``api/db_models.py`` against a database at ``33ff7e590a46``; the backfill below
is hand-written.

Backfill: every card already ``saved`` gets a row, ``already_tracked`` (finished
now) when the card has a tracked company, else ``queued``. The legacy
``launch_radar_cards.pr_url`` column is IGNORED: the only values in it point at
closed PRs of the removed PR step, and a closed PR does not block a fresh one.

Downgrade drops the indexes and the table, so the PR queue and every recorded
PR link are lost (the PRs themselves stay on GitHub).

Autogenerate does not compare CHECK constraints on an existing table, so
``api/tests/test_db_models.py`` pins the status and PR-URL CHECK text against
this file.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c4d1370996'
down_revision: Union[str, None] = '33ff7e590a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launch_radar_pr_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pr_url', sa.Text(), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('last_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retry_after', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'open') = (pr_url IS NOT NULL)", name='ck_launch_radar_pr_requests_open'),
    sa.CheckConstraint("pr_url IS NULL OR pr_url ~ '^https://github\\.com/brendanpotter00/Job-Visualizer-Notifier/pull/[0-9]+$'", name='ck_launch_radar_pr_requests_pr_url'),
    sa.CheckConstraint("status IN ('queued','in_progress','open','failed','no_board','already_tracked','cancelled')", name='ck_launch_radar_pr_requests_status'),
    sa.CheckConstraint('(pr_url IS NULL) = (pr_number IS NULL)', name='ck_launch_radar_pr_requests_pr_pair'),
    sa.CheckConstraint('attempts >= 0', name='ck_launch_radar_pr_requests_attempts'),
    sa.ForeignKeyConstraint(['card_id'], ['launch_radar_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', name='uq_launch_radar_pr_requests_card_id')
    )
    op.create_index('idx_launch_radar_pr_requests_status_requested', 'launch_radar_pr_requests', ['status', 'requested_at'], unique=False)
    op.create_index('uq_launch_radar_pr_requests_pr_url', 'launch_radar_pr_requests', ['pr_url'], unique=True, postgresql_where=sa.text('pr_url IS NOT NULL'))
    # ### end Alembic commands ###
    # Backfill (hand-written): a row for every card already saved. The legacy
    # launch_radar_cards.pr_url is deliberately not read.
    op.execute(
        "INSERT INTO launch_radar_pr_requests (card_id, status, requested_at, finished_at, updated_at) "
        "SELECT c.id, "
        "CASE WHEN c.tracked_company_id IS NOT NULL THEN 'already_tracked' ELSE 'queued' END, "
        "now(), "
        "CASE WHEN c.tracked_company_id IS NOT NULL THEN now() END, "
        "now() "
        "FROM launch_radar_cards c "
        "WHERE c.status = 'saved' "
        "ON CONFLICT (card_id) DO NOTHING"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_launch_radar_pr_requests_pr_url', table_name='launch_radar_pr_requests', postgresql_where=sa.text('pr_url IS NOT NULL'))
    op.drop_index('idx_launch_radar_pr_requests_status_requested', table_name='launch_radar_pr_requests')
    op.drop_table('launch_radar_pr_requests')
    # ### end Alembic commands ###
