"""add user_visits table

Revision ID: 0df6e1b45b6c
Revises: 9eec908e87cd
Create Date: 2026-06-25 14:00:00.000000+00:00

Append-only per-visit log (one row per POST /api/users/visit — one full page
load / refresh, NOT SPA route navigation). Backs the admin roster's clickable
"Visits" modal. The denormalized users.visit_count / last_visit_at counters are
KEPT (the roster query + sort are unchanged); this table only ADDS individual-
visit history.

Brand-new table + a tiny one-time backfill: no rewrite or lock of the existing
`users` table, so this cannot reproduce the 2026-04-18 volume incident (that was
an ALTER on a large table). The combined-ALTER-TABLE rule (see
docs/incidents/2026-04-18-migration-filled-postgres-volume/) applies to adding
columns to an existing table, not to CREATE TABLE, so the autogenerated
op.create_table form is kept as-is (matching the admins / location tables prior
art and, crucially, Base.metadata.create_all for the alembic-parity test).

Surrogate BIGINT (BIGSERIAL) PK because the log has no natural client id —
contrast users.id, a Python-generated uuid hex Text. The (user_id, visited_at)
btree serves the modal's "ORDER BY visited_at DESC" via a backward index scan,
so no descending index is needed.

HISTORICAL-DATA CAVEAT / BACKFILL: existing users already have visit_count > 0
but no rows here — per-visit history begins at this migration. We seed ONE row
per user from their single known last_visit_at so currently-active users aren't
empty on day one; the earlier visits are unrecoverable, so the modal surfaces
the count-vs-history gap with a caption ("Showing X of Y visits").
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df6e1b45b6c'
down_revision: Union[str, None] = '9eec908e87cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_visits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('visited_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_visits_user_id_visited_at', 'user_visits', ['user_id', 'visited_at'], unique=False)
    # ### end Alembic commands ###

    # One-time backfill (NOT autogenerated): seed each existing user's single
    # known visit timestamp so the new modal isn't empty for already-active
    # users on launch day. Only last_visit_at is recoverable — pre-launch
    # visits beyond the most recent one have no stored timestamp.
    op.execute(
        "INSERT INTO user_visits (user_id, visited_at)"
        " SELECT id, last_visit_at FROM users WHERE last_visit_at IS NOT NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_visits_user_id_visited_at', table_name='user_visits')
    op.drop_table('user_visits')
    # ### end Alembic commands ###
