"""add location normalization tables

Revision ID: c876c313e55c
Revises: c4f0a2d8b9e1
Create Date: 2026-06-08 03:41:57.058724+00:00

Additive schema for the location-normalization pipeline (Unit 2). Creates four
new tables — locations, location_aliases, alias_locations, job_locations — plus
one nullable column job_listings.normalization_status (NULL|'pending'|'done'|
'failed'). The column add is catalog-only: nullable, no default backfill, no USING
clause, so it cannot rewrite the 44,666-row job_listings table (combined-ALTER-TABLE
rule; see docs/incidents/2026-04-18-migration-filled-postgres-volume/).

Procrastinate's runtime tables (procrastinate_jobs / _events / _periodic_defers)
are intentionally NOT in this diff — Procrastinate manages its own schema via
ensure_schema_async at startup. This migration was autogenerated against a
reference database that does not contain those runtime tables, so no phantom
drops were produced and none had to be stripped (matching the filtering
documented for revisions 2aaec46888f4 and the 20260519 series).

job_locations.job_listing_id has NO database foreign key. job_listings' primary
key is the COMPOSITE (source_id, id), and there is no UNIQUE/PK constraint on
`id` alone, so a single-column FK to job_listings(id) would be invalid Postgres.
We deliberately key job_locations by job_listing_id alone (matches the plan's
worked examples and lets later units operate with just job_id) and enforce
referential integrity at the application layer. This is safe because
job_listings.id is globally unique in practice (verified: 0 collisions across
44,666 prod rows). normalized_location_id keeps a real FK because locations.id is
a single-column primary key. Do not "fix" the missing FK by adding a UNIQUE on
job_listings.id — that would reverse the locked composite-key decision.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c876c313e55c'
down_revision: Union[str, None] = 'c4f0a2d8b9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_aliases',
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('raw_text')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('remote_scope', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'city', 'region', 'country', 'remote_scope', name='uq_locations_canonical')
    )
    op.create_table('alias_locations',
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_location_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['normalized_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['raw_text'], ['location_aliases.raw_text'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('raw_text', 'normalized_location_id')
    )
    op.create_table('job_locations',
    sa.Column('job_listing_id', sa.Text(), nullable=False),
    sa.Column('normalized_location_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['normalized_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('job_listing_id', 'normalized_location_id')
    )
    op.create_index('idx_job_locations_job_listing_id', 'job_locations', ['job_listing_id'], unique=False)
    op.add_column('job_listings', sa.Column('normalization_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_listings', 'normalization_status')
    op.drop_index('idx_job_locations_job_listing_id', table_name='job_locations')
    op.drop_table('job_locations')
    op.drop_table('alias_locations')
    op.drop_table('locations')
    op.drop_table('location_aliases')
    # ### end Alembic commands ###
