"""add enrichment-claim first_seen_at ordering index

Revision ID: 8e59adfb817a
Revises: 695acc9f478b
Create Date: 2026-07-12 16:00:00.000000+00:00

Supports the /pending claim ordering (internal_enrichment.py): the claim orders
the claimable set by ``first_seen_at DESC`` so the enricher labels the freshest
jobs first — the property that matters once a low-throughput local model can only
drain ~limit rows per tick out of a deep (~19k OPEN unenriched) backlog.

``idx_job_listings_enrichment_claim`` — PARTIAL btree on ``first_seen_at`` WHERE
``enrichment_status IS NULL AND status = 'OPEN'``. Predicate mirrors the claim
subquery exactly, so the planner index-scans it backward for the ``DESC`` order
and stops at ``LIMIT`` instead of sorting the whole backlog.

Plain (non-CONCURRENT) ``create_index`` — Alembic runs migrations in a
transaction, and the predicate is partial (only the ~19k claimable rows are
indexed, not the whole ~57k-row table), so the build is sub-second and does not
rewrite the table (contrast the 2026-04-18 volume incident, which was full-table
ALTER COLUMN rewrites).

Autogenerated from ``db_models.py::JobListing.__table_args__``.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8e59adfb817a'
down_revision: Union[str, None] = '695acc9f478b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index('idx_job_listings_enrichment_claim', 'job_listings', ['first_seen_at'], unique=False, postgresql_where=sa.text("enrichment_status IS NULL AND status = 'OPEN'"))


def downgrade() -> None:
    op.drop_index('idx_job_listings_enrichment_claim', table_name='job_listings', postgresql_where=sa.text("enrichment_status IS NULL AND status = 'OPEN'"))
