"""add job_freshness sidecar table

Revision ID: 01fef5c9c582
Revises: a1b2c3d4e5f6
Create Date: 2026-07-13 13:34:11.889750+00:00

Expand phase (step 1 of the expand -> migrate -> contract rollout) for the
2026-07-13 ``/api/jobs`` outage fix. Creates the narrow ``job_freshness``
sidecar that will own the two high-churn columns (``last_seen_at``,
``consecutive_misses``) so the wide, TOAST-heavy ``job_listings`` table stops
being rewritten on every hourly scrape cycle (that churn bloated
``idx_job_listings_last_seen`` to 100 MB for 58k rows and pushed the
``ORDER BY last_seen_at DESC`` read past the 30 s statement timeout).

This revision is **purely additive** — no read or write path uses the sidecar
yet. It only stands up the table and, critically, the DB-level guarantees that
make the two tables unable to drift:

  * A composite FK ``(source_id, id) -> job_listings(source_id, id)`` with
    ``ON DELETE CASCADE`` (no orphaned freshness rows).
  * An ``AFTER INSERT`` trigger on ``job_listings`` that materialises the
    matching freshness row for *every* new listing, regardless of which code
    path inserted it. This makes the read-side INNER JOIN (Unit 3) lossless by
    construction — the application only ever has to keep the row *fresh*, never
    to remember to *create* it.
  * A one-shot backfill for the ~58k existing rows, plus a loud post-backfill
    invariant check that aborts the migration if any listing lacks a freshness
    row.

The trigger seeds ``last_seen_at`` from ``NEW.first_seen_at`` and a literal ``0``
for ``consecutive_misses`` (never ``NEW.last_seen_at`` / ``NEW.consecutive_misses``)
so it keeps working unchanged after the contract migration (Unit 4) drops those
two columns from ``job_listings``. The backfill, by contrast, copies each
existing row's *current* ``last_seen_at`` so freshness starts out accurate.

Storage params (``fillfactor`` + aggressive autovacuum) are applied so this tiny
table's heap and ``last_seen_at`` index stay tight under constant churn — the
mechanism that could not keep up on the 600 MB parent works here precisely
because the table is small.

Ordering within ``upgrade()`` is deliberate and race-safe: create table -> set
storage params -> install trigger -> backfill. Any listing inserted while the
migration runs is caught by the trigger, and the backfill's
``ON CONFLICT DO NOTHING`` tolerates the overlap. No table rewrite of
``job_listings`` occurs (see docs/incidents/2026-04-18-migration-filled-postgres-volume/).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fef5c9c582'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Table + composite FK + ordering index (autogenerated) -------------
    op.create_table(
        'job_freshness',
        sa.Column('source_id', sa.Text(), nullable=False),
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('consecutive_misses', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.ForeignKeyConstraint(
            ['source_id', 'id'],
            ['job_listings.source_id', 'job_listings.id'],
            name='job_freshness_job_listings_fkey',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('source_id', 'id'),
    )
    op.create_index('idx_job_freshness_last_seen', 'job_freshness', ['last_seen_at'], unique=False)

    # --- Storage params: keep this hot little table's heap + index tight ----
    # fillfactor leaves in-page slack so consecutive_misses-only updates (which
    # touch no index) can go HOT; the aggressive autovacuum scale factors make
    # vacuum run after ~1k dead tuples instead of ~20% of the table, so the
    # last_seen_at index never accumulates the bloat that sank the parent.
    op.execute(
        """
        ALTER TABLE job_freshness SET (
            fillfactor = 90,
            autovacuum_vacuum_scale_factor = 0.02,
            autovacuum_analyze_scale_factor = 0.02
        )
        """
    )

    # --- Anti-drift trigger: every new listing gets a freshness row ---------
    # Uses NEW.first_seen_at (not last_seen_at) and a literal 0 so it survives
    # the Unit 4 contract migration that drops last_seen_at / consecutive_misses
    # from job_listings. For a genuinely new job first_seen_at == the scrape
    # time, so this is the correct initial freshness. ON CONFLICT DO NOTHING
    # makes it idempotent against the backfill below and any re-run.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION job_freshness_sync() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            INSERT INTO job_freshness (source_id, id, last_seen_at, consecutive_misses)
            VALUES (NEW.source_id, NEW.id, NEW.first_seen_at, 0)
            ON CONFLICT (source_id, id) DO NOTHING;
            RETURN NULL;  -- AFTER trigger: return value is ignored
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER job_freshness_sync_after_insert
            AFTER INSERT ON job_listings
            FOR EACH ROW
            EXECUTE FUNCTION job_freshness_sync()
        """
    )

    # --- Backfill existing rows (trivial: ~58k narrow rows) -----------------
    # Copies each listing's CURRENT last_seen_at / consecutive_misses so
    # freshness starts out accurate (the trigger's first_seen_at seed is only
    # right for brand-new rows). ON CONFLICT DO NOTHING tolerates any row the
    # trigger already inserted for a concurrent insert during the migration.
    op.execute(
        """
        INSERT INTO job_freshness (source_id, id, last_seen_at, consecutive_misses)
        SELECT source_id, id, last_seen_at, COALESCE(consecutive_misses, 0)
        FROM job_listings
        ON CONFLICT (source_id, id) DO NOTHING
        """
    )

    # --- Loud invariant check: no listing may be missing its freshness row --
    op.execute(
        """
        DO $$
        DECLARE
            missing int;
        BEGIN
            SELECT count(*) INTO missing
            FROM job_listings l
            LEFT JOIN job_freshness f
              ON f.source_id = l.source_id AND f.id = l.id
            WHERE f.source_id IS NULL;
            IF missing > 0 THEN
                RAISE EXCEPTION
                    'job_freshness backfill incomplete: % job_listings row(s) '
                    'have no freshness row', missing;
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    # Reverse order: trigger + function first (they depend on the table), then
    # the autogenerated index + table drop. IF EXISTS keeps downgrade safe on a
    # partially-applied revision.
    op.execute("DROP TRIGGER IF EXISTS job_freshness_sync_after_insert ON job_listings")
    op.execute("DROP FUNCTION IF EXISTS job_freshness_sync()")
    op.drop_index('idx_job_freshness_last_seen', table_name='job_freshness')
    op.drop_table('job_freshness')
