"""add blurb and accomplishment to companies

Revision ID: e015cd4d01a8
Revises: c7d2e9f4a1b8
Create Date: 2026-06-20 03:30:54.871640+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e015cd4d01a8'
down_revision: Union[str, None] = 'c7d2e9f4a1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Combined ALTER TABLE (one statement) — adjusted from the two autogenerated
    # op.add_column calls per the combined-ALTER-TABLE rule (see
    # docs/implementations/alembicMigration/DEPLOY.md and the 2026-04-18
    # postmortem), matching the 204a7e074899 prior art. Both columns are nullable
    # with no default, so this is a metadata-only change (no table rewrite).
    op.execute("ALTER TABLE companies ADD COLUMN blurb TEXT, ADD COLUMN accomplishment TEXT")


def downgrade() -> None:
    op.execute("ALTER TABLE companies DROP COLUMN accomplishment, DROP COLUMN blurb")
