"""seed workday companies

Revision ID: b9714f608e21
Revises: 08e719b2aa03
Create Date: 2026-05-19 15:43:55.335041+00:00

Data-only seed migration for the 11 Workday-hosted companies.

**Rebase coordination with sibling backend-migration PRs:**
  This revision was originally autogenerated to also add the
  ``provider_config`` JSONB column to the ``companies`` table. During the
  PR #123 → main merge the Eightfold migration (#124) had already landed,
  introducing the same column with the same definition
  (``JSONB NOT NULL DEFAULT '{}'::jsonb``) as part of its own combined
  schema + seed revision. To keep Alembic to a single head and avoid a
  duplicate ``op.add_column``, ``down_revision`` was rebased from
  ``b29c1ef8800600`` (Gem) to ``08e719b2aa03`` (Eightfold) and the
  ``op.add_column`` / ``op.drop_column`` calls were stripped from this
  file. The chain is now Ashby → Lever → Gem → Eightfold → Workday.

  Eightfold's migration anticipated this exact resolution — see its
  module docstring around lines 14–32 ("If Workday PR #123 merges first
  ... the mechanical rebase is: drop the ``op.add_column`` ...").

Seeds 11 Workday rows. Source of truth at the time of writing:
  src/frontend/src/config/companies.ts (Workday block, lines ~532-614)

Hand-written data migration (the documented exception to the
autogenerate-only rule). Alembic's --autogenerate diffs schema, not data,
so the per-company config blobs have to be transcribed by hand.

Future Workday adds should be made via a new migration, NOT by editing
this one — frozen migrations stay frozen.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9714f608e21'
down_revision: Union[str, None] = '08e719b2aa03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Workday seed rows. `provider_config` is the per-row JSONB blob the
# Procrastinate fetch task reads to construct the POST URL + body.
# `default_facets` is optional; only NVIDIA and Adobe set it today (used
# to narrow the result set to the US Engineering / University population).
WORKDAY_SEED_ROWS: list[dict] = [
    {
        'id': 'nvidia',
        'display_name': 'NVIDIA',
        'board_token': 'nvidia',
        'provider_config': {
            'base_url': 'https://nvidia.wd5.myworkdayjobs.com',
            'tenant_slug': 'nvidia',
            'career_site_slug': 'NVIDIAExternalCareerSite',
            'default_facets': {
                'locationHierarchy1': ['2fcb99c455831013ea52fb338f2932d8'],
                'jobFamilyGroup': ['0c40f6bd1d8f10ae43ffaefd46dc7e78'],
                'timeType': ['5509c0b5959810ac0029943377d47364'],
            },
        },
    },
    {
        'id': 'adobe',
        'display_name': 'Adobe',
        'board_token': 'adobe',
        'provider_config': {
            'base_url': 'https://adobe.wd5.myworkdayjobs.com',
            'tenant_slug': 'adobe',
            'career_site_slug': 'external_experienced',
            'default_facets': {
                'locationCountry': ['bc33aa3152ec42d4995f4791a106ed09'],
                'jobFamilyGroup': [
                    '591af8b812fa10737af39db3d96eed9f',
                    '591af8b812fa10737b43a1662896f01c',
                ],
            },
        },
    },
    {
        'id': 'expedia',
        'display_name': 'Expedia',
        'board_token': 'expedia',
        'provider_config': {
            'base_url': 'https://expedia.wd108.myworkdayjobs.com',
            'tenant_slug': 'expedia',
            'career_site_slug': 'search',
        },
    },
    {
        'id': 'turo',
        'display_name': 'Turo',
        'board_token': 'turo',
        'provider_config': {
            'base_url': 'https://turo.wd12.myworkdayjobs.com',
            'tenant_slug': 'turo',
            'career_site_slug': 'Turo_careers',
        },
    },
    {
        'id': 'blueorigin',
        'display_name': 'Blue Origin',
        'board_token': 'blueorigin',
        'provider_config': {
            'base_url': 'https://blueorigin.wd5.myworkdayjobs.com',
            'tenant_slug': 'blueorigin',
            'career_site_slug': 'BlueOrigin',
        },
    },
    {
        'id': 'snap',
        'display_name': 'Snap',
        'board_token': 'snap',
        'provider_config': {
            'base_url': 'https://snapchat.wd1.myworkdayjobs.com',
            'tenant_slug': 'snapchat',
            'career_site_slug': 'snap',
        },
    },
    {
        'id': 'gm',
        'display_name': 'General Motors',
        'board_token': 'gm',
        'provider_config': {
            'base_url': 'https://generalmotors.wd5.myworkdayjobs.com',
            'tenant_slug': 'generalmotors',
            'career_site_slug': 'Careers_GM',
        },
    },
    {
        'id': 'disney',
        'display_name': 'Disney',
        'board_token': 'disney',
        'provider_config': {
            'base_url': 'https://disney.wd5.myworkdayjobs.com',
            'tenant_slug': 'disney',
            'career_site_slug': 'disneycareer',
        },
    },
    {
        'id': 'slack',
        'display_name': 'Slack',
        'board_token': 'slack',
        'provider_config': {
            'base_url': 'https://salesforce.wd12.myworkdayjobs.com',
            'tenant_slug': 'salesforce',
            'career_site_slug': 'Slack',
        },
    },
    {
        'id': 'capitalone',
        'display_name': 'Capital One',
        'board_token': 'capitalone',
        'provider_config': {
            'base_url': 'https://capitalone.wd12.myworkdayjobs.com',
            'tenant_slug': 'capitalone',
            'career_site_slug': 'Capital_One',
        },
    },
    {
        'id': 'paypal',
        'display_name': 'PayPal',
        'board_token': 'paypal',
        'provider_config': {
            'base_url': 'https://paypal.wd1.myworkdayjobs.com',
            'tenant_slug': 'paypal',
            'career_site_slug': 'jobs',
        },
    },
]


def upgrade() -> None:
    # --- Data seed (hand-written, documented exception to autogen-only rule) ---
    # The ``provider_config`` column was added by the Eightfold migration
    # (``08e719b2aa03``); see this module's docstring for the rebase
    # rationale. This revision only seeds the 11 Workday rows.
    #
    # ON CONFLICT (id) DO NOTHING for idempotency: if any of these rows were
    # backfilled out-of-band (manual repair, partial prior run, prod hotfix),
    # the seed migration must NOT trip a PK-conflict and brick startup.
    # Re-running this migration after manual repair is a supported workflow.
    bind = op.get_bind()
    insert_sql = sa.text(
        "INSERT INTO companies (id, display_name, ats, board_token, provider_config) "
        "VALUES (:id, :display_name, 'workday', :board_token, CAST(:provider_config AS jsonb)) "
        "ON CONFLICT (id) DO NOTHING"
    )
    for row in WORKDAY_SEED_ROWS:
        bind.execute(
            insert_sql,
            {
                'id': row['id'],
                'display_name': row['display_name'],
                'board_token': row['board_token'],
                # psycopg2 / SQLAlchemy can't bind a dict directly into the
                # JSONB parameter via the text() interface — serialize to JSON
                # and use an explicit CAST in the SQL above. Same idiom used
                # by the Greenhouse/Ashby/Lever/Gem seeds for symmetry.
                'provider_config': _to_json(row['provider_config']),
            },
        )


def downgrade() -> None:
    # Scoped DELETE — must NOT touch Greenhouse / Ashby / Lever / Gem /
    # Eightfold rows or any out-of-band rows with other ats values. The
    # ``provider_config`` column is owned by the Eightfold migration; we
    # do not drop it here.
    op.execute("DELETE FROM companies WHERE ats = 'workday'")


def _to_json(value: dict) -> str:
    """Serialize a dict to a JSON string for the CAST(... AS jsonb) bind.

    Standalone so the import stays at the function-call level and the
    revision file doesn't need a `json` import at module load time
    (Alembic loads every revision module to build the dependency graph; we
    keep these light).
    """
    import json
    return json.dumps(value)
