"""add enrichment tables and job_listings columns

Autogenerated, then reviewed per src/backend/CLAUDE.md:
  - stripped the phantom procrastinate_* drop/recreate ops (those tables are
    owned by Procrastinate's own schema setup, not Base.metadata);
  - collapsed the four job_listings column adds into ONE combined, catalog-only
    ALTER TABLE (all nullable, no default backfill -> a catalog-only metadata
    change, no table rewrite regardless of row count; see
    docs/incidents/2026-04-18-migration-filled-postgres-volume/);
  - added the job_categories / job_levels dimension seeds (autogenerate does not
    emit data). new_grad's parent is entry -> the "entry" filter expands to
    {entry, new_grad}, the load-bearing hierarchy case.

Revision ID: 0fa33aca5bda
Revises: 61a2e3f761b9
Create Date: 2026-07-01 03:58:48.128348+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0fa33aca5bda'
down_revision: Union[str, None] = '61a2e3f761b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


CATEGORY_SEED = [
    ("software_engineering", "Software Engineering", 0),
    ("hardware_engineer", "Hardware Engineer", 1),
    ("product_manager", "Product Manager", 2),
    ("project_manager", "Project Manager", 3),
    ("growth", "Growth", 4),
    ("business_ops", "Business Ops", 5),
]

# (slug, label, rank, parent_slug)
LEVEL_SEED = [
    ("new_grad", "New Grad", 0, "entry"),
    ("entry", "Entry", 1, None),
    ("mid", "Mid", 2, None),
    ("senior", "Senior", 3, None),
    ("senior_plus", "Staff / Principal", 4, None),
    ("manager", "Manager", 5, None),
]


def upgrade() -> None:
    # 1. Dimension + join + side tables (dims are FK targets, created first).
    op.create_table(
        'job_categories',
        sa.Column('slug', sa.Text(), nullable=False),
        sa.Column('label', sa.Text(), nullable=False),
        sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
        sa.PrimaryKeyConstraint('slug'),
    )
    op.create_table(
        'job_levels',
        sa.Column('slug', sa.Text(), nullable=False),
        sa.Column('label', sa.Text(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('parent_slug', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['parent_slug'], ['job_levels.slug'], ),
        sa.PrimaryKeyConstraint('slug'),
    )
    op.create_table(
        'job_tags',
        sa.Column('source_id', sa.Text(), nullable=False),
        sa.Column('job_listing_id', sa.Text(), nullable=False),
        sa.Column('tag', sa.Text(), nullable=False),
        # Composite key on (source_id, job_listing_id, tag): job_listings' PK is
        # (source_id, id) and `id` is NOT globally unique, so tags must be keyed
        # by the full composite to stay collision-safe when two sources share an
        # id. No FK — the composite PK on job_listings blocks a single-col FK.
        sa.PrimaryKeyConstraint('source_id', 'job_listing_id', 'tag'),
    )
    op.create_index('idx_job_tags_tag', 'job_tags', ['tag'], unique=False)
    op.create_table(
        'job_enrichment',
        sa.Column('source_id', sa.Text(), nullable=False),
        sa.Column('job_listing_id', sa.Text(), nullable=False),
        sa.Column('clean_description', sa.Text(), nullable=True),
        sa.Column('classify_confidence', sa.Float(), nullable=True),
        sa.Column('classify_reasoning', sa.Text(), nullable=True),
        sa.Column('taxonomy_version', sa.Text(), nullable=True),
        sa.Column('judged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('judge_passed', sa.Boolean(), nullable=True),
        sa.Column('judge_confidence', sa.Float(), nullable=True),
        sa.Column('judge_notes', sa.Text(), nullable=True),
        sa.Column('needs_human', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('enriched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        # Composite key on (source_id, job_listing_id) — same rationale as
        # job_tags: `id` is not globally unique under the (source_id, id) PK.
        sa.PrimaryKeyConstraint('source_id', 'job_listing_id'),
    )
    op.create_index('idx_job_enrichment_needs_human', 'job_enrichment', ['needs_human'], unique=False)

    # 2. Seed the dimensions (idempotent). Parents before children for the self-FK.
    bind = op.get_bind()
    cat_insert = sa.text(
        "INSERT INTO job_categories (slug, label, sort_order) "
        "VALUES (:slug, :label, :sort_order) ON CONFLICT (slug) DO NOTHING"
    )
    for slug, label, sort_order in CATEGORY_SEED:
        bind.execute(cat_insert, {"slug": slug, "label": label, "sort_order": sort_order})
    lvl_insert = sa.text(
        "INSERT INTO job_levels (slug, label, rank, parent_slug) "
        "VALUES (:slug, :label, :rank, :parent) ON CONFLICT (slug) DO NOTHING"
    )
    for slug, label, rank, parent in sorted(LEVEL_SEED, key=lambda r: r[3] is not None):
        bind.execute(lvl_insert, {"slug": slug, "label": label, "rank": rank, "parent": parent})

    # 3. Combined, catalog-only ALTER on the large table (single statement, all
    #    nullable, no default -> no rewrite; FK columns validate trivially since
    #    every value is NULL).
    op.execute(
        """
        ALTER TABLE job_listings
            ADD COLUMN enrichment_status     TEXT,
            ADD COLUMN enrichment_category   TEXT REFERENCES job_categories (slug),
            ADD COLUMN enrichment_level      TEXT REFERENCES job_levels (slug),
            ADD COLUMN enrichment_claimed_at TIMESTAMP WITH TIME ZONE
        """
    )
    op.create_index('idx_job_listings_enrichment_status', 'job_listings', ['enrichment_status'], unique=False)
    op.create_index('idx_job_listings_status_category', 'job_listings', ['status', 'enrichment_category'], unique=False)
    op.create_index('idx_job_listings_status_level', 'job_listings', ['status', 'enrichment_level'], unique=False)


def downgrade() -> None:
    # Drop the three enrichment indexes explicitly first for clarity — Postgres
    # would also auto-drop them when their columns are dropped (an index is
    # dropped when ANY of its columns is dropped, multicolumn included) — then the
    # job_listings columns (dropping a column also cascades its own inline FK),
    # then the dimension tables. Scoped — touches nothing pre-existing.
    op.drop_index('idx_job_listings_status_level', table_name='job_listings')
    op.drop_index('idx_job_listings_status_category', table_name='job_listings')
    op.drop_index('idx_job_listings_enrichment_status', table_name='job_listings')
    op.drop_column('job_listings', 'enrichment_claimed_at')
    op.drop_column('job_listings', 'enrichment_level')
    op.drop_column('job_listings', 'enrichment_category')
    op.drop_column('job_listings', 'enrichment_status')
    op.drop_index('idx_job_enrichment_needs_human', table_name='job_enrichment')
    op.drop_table('job_enrichment')
    op.drop_index('idx_job_tags_tag', table_name='job_tags')
    op.drop_table('job_tags')
    op.drop_table('job_levels')
    op.drop_table('job_categories')
