"""launch radar tables

Revision ID: 33ff7e590a46
Revises: 904d5bc44e4b
Create Date: 2026-10-07 17:20:57.783276+00:00

The four Launch Radar tables (docs/implementations/launch-radar/CONTRACT.md):
runs, the append-only spend ledger, the Parallel monitors, and one card per
normalized domain (statuses new / saved / archived / deleted). Autogenerated
from ``api/db_models.py`` against a database at ``904d5bc44e4b``.

``launch_radar_cards.tracked_company_id`` is a soft link to ``companies.id``
(house style, no FK). The only foreign keys are inside these tables:
``launch_radar_cards.run_id`` and ``launch_radar_spend.run_id`` reference
``launch_radar_runs.id``.

Autogenerate does not compare CHECK constraints on an existing table, so
``api/tests/test_db_models.py`` pins the card status CHECK text against this
file.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33ff7e590a46'
down_revision: Union[str, None] = '904d5bc44e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('launch_radar_monitors',
    sa.Column('slot', sa.Text(), nullable=False),
    sa.Column('monitor_id', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('processor', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('last_event_id', sa.Text(), nullable=True),
    sa.Column('charged_through', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slot IN ('seed','series_a_plus','launch')", name='ck_launch_radar_monitors_slot'),
    sa.CheckConstraint("status IN ('active','cancelled')", name='ck_launch_radar_monitors_status'),
    sa.PrimaryKeyConstraint('slot'),
    sa.UniqueConstraint('monitor_id', name='uq_launch_radar_monitors_monitor_id')
    )
    op.create_table('launch_radar_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('budget_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('events_read', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cards_posted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running','ok','stopped','error')", name='ck_launch_radar_runs_status'),
    sa.CheckConstraint('budget_usd > 0', name='ck_launch_radar_runs_budget'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_uuid', name='uq_launch_radar_runs_run_uuid')
    )
    op.create_index('idx_launch_radar_runs_started_at', 'launch_radar_runs', ['started_at'], unique=False)
    op.create_table('launch_radar_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'new'"), nullable=False),
    sa.Column('tracked_company_id', sa.Text(), nullable=True),
    sa.Column('pr_url', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.CheckConstraint("(status = 'deleted') = (payload IS NULL)", name='ck_launch_radar_cards_tombstone'),
    sa.CheckConstraint("status <> 'deleted' OR (pr_url IS NULL AND tracked_company_id IS NULL)", name='ck_launch_radar_cards_tombstone_clean'),
    sa.CheckConstraint("status IN ('new','saved','archived','deleted')", name='ck_launch_radar_cards_status'),
    sa.CheckConstraint('domain = lower(domain)', name='ck_launch_radar_cards_domain_lower'),
    sa.ForeignKeyConstraint(['run_id'], ['launch_radar_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', name='uq_launch_radar_cards_domain')
    )
    op.create_index('idx_launch_radar_cards_status_posted', 'launch_radar_cards', ['status', 'posted_at'], unique=False)
    op.create_table('launch_radar_spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('accrued', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_usd > 0', name='ck_launch_radar_spend_amount'),
    sa.ForeignKeyConstraint(['run_id'], ['launch_radar_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_launch_radar_spend_run_id', 'launch_radar_spend', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_launch_radar_spend_run_id', table_name='launch_radar_spend')
    op.drop_table('launch_radar_spend')
    op.drop_index('idx_launch_radar_cards_status_posted', table_name='launch_radar_cards')
    op.drop_table('launch_radar_cards')
    op.drop_index('idx_launch_radar_runs_started_at', table_name='launch_radar_runs')
    op.drop_table('launch_radar_runs')
    op.drop_table('launch_radar_monitors')
    # ### end Alembic commands ###
