"""add visit_count and last_visit_at to users

Revision ID: 7ccc685e2cd6
Revises: ebe8cd35b4cd
Create Date: 2026-06-23 01:37:49.458573+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccc685e2cd6'
down_revision: Union[str, None] = 'ebe8cd35b4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Combined ALTER TABLE (one statement) — collapsed from the two
    # autogenerated op.add_column calls per the combined-ALTER-TABLE rule (see
    # docs/implementations/alembicMigration/DEPLOY.md and the 2026-04-18
    # postmortem), matching the e015cd4d01a8 / 204a7e074899 prior art.
    # visit_count has a constant DEFAULT and last_visit_at is nullable with no
    # default, so this is a metadata-only change (no table rewrite); existing
    # rows backfill to visit_count=0, last_visit_at=NULL.
    op.execute(
        "ALTER TABLE users "
        "ADD COLUMN visit_count INTEGER NOT NULL DEFAULT 0, "
        "ADD COLUMN last_visit_at TIMESTAMP WITH TIME ZONE"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE users "
        "DROP COLUMN last_visit_at, "
        "DROP COLUMN visit_count"
    )
