"""add company_enroll_watermark and auto_enroll_new_companies to users

Revision ID: 204a7e074899
Revises: 1e35a6d3cb28
Create Date: 2026-05-27 13:09:58.148984+00:00

Adds the two per-user columns that drive auto-enroll into newly-added
companies:

- ``company_enroll_watermark`` — companies created after this timestamp
  auto-enroll on read; bumped to ``now()`` on every save so opt-outs stick.
- ``auto_enroll_new_companies`` — the global on/off toggle (default true).

Autogenerate emits two separate ``op.add_column`` calls; they are collapsed
here into a single ``ALTER TABLE`` so the ``now()`` (volatile) default forces
at most ONE table rewrite + one WAL stream rather than two, per the
combined-ALTER-TABLE rule from
``docs/incidents/2026-04-18-migration-filled-postgres-volume/``. ``users`` is
tiny so the rewrite is cheap; the rewrite is what backfills existing users'
watermark to launch time (the forward-only behavior).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204a7e074899'
down_revision: Union[str, None] = '1e35a6d3cb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Combined ALTER TABLE (one rewrite) — adjusted from the two autogenerated
    # op.add_column calls per the combined-ALTER-TABLE rule (see module docstring).
    op.execute(
        "ALTER TABLE users "
        "ADD COLUMN company_enroll_watermark TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "
        "ADD COLUMN auto_enroll_new_companies BOOLEAN NOT NULL DEFAULT true"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE users "
        "DROP COLUMN auto_enroll_new_companies, "
        "DROP COLUMN company_enroll_watermark"
    )
